# Generated by Django 5.2.8 on 2025-11-14 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('humanResources', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('birth_place', models.ForeignKey(db_column='birth_place_code', on_delete=django.db.models.deletion.PROTECT, to='locations.city')),
                ('campus', models.ForeignKey(db_column='campus_code', on_delete=django.db.models.deletion.CASCADE, to='locations.campus')),
                ('contract_type', models.ForeignKey(db_column='contract_type', on_delete=django.db.models.deletion.PROTECT, to='humanResources.contracttype')),
                ('employee_type', models.ForeignKey(db_column='employee_type', on_delete=django.db.models.deletion.PROTECT, to='humanResources.employeetype')),
                ('faculty', models.ForeignKey(db_column='faculty_code', on_delete=django.db.models.deletion.CASCADE, to='locations.faculty')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('birth_place', models.ForeignKey(db_column='birth_place_code', on_delete=django.db.models.deletion.PROTECT, to='locations.city')),
                ('campus', models.ForeignKey(db_column='campus_code', on_delete=django.db.models.deletion.CASCADE, to='locations.campus')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=100)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('employee', models.OneToOneField(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.employee')),
                ('student', models.OneToOneField(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.student')),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', True), ('student__isnull', False)), models.Q(('employee__isnull', False), ('student__isnull', True)), _connector='OR'), name='USERS_ONE_ROLE_CHK')],
            },
        ),
    ]
