# Generated by Django 5.2.8 on 2025-11-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contract_types',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employee_types',
            },
        ),
    ]
