# Generated by Django 5.2.8 on 2025-11-09 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cardio', 'Cardio'), ('fuerza', 'Fuerza'), ('movilidad', 'Movilidad')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('difficulty', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('video_url', models.URLField(blank=True)),
                ('created_by', models.CharField(default='system', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fitness_exercises',
            },
        ),
        migrations.CreateModel(
            name='ProgressSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('routine_id', models.IntegerField(blank=True, null=True)),
                ('exercise_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('effort_level', models.IntegerField(help_text='1-10 scale')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fitness_progress',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('routine_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fitness_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('exercises', models.JSONField(default=list)),
                ('created_by', models.CharField(max_length=50)),
                ('is_pre_designed', models.BooleanField(default=False)),
                ('base_routine_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fitness_routines',
            },
        ),
    ]
