# Generated by Django 5.2.8 on 2025-11-07 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('dean_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
            options={
                'db_table': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.ForeignKey(db_column='city_code', on_delete=django.db.models.deletion.CASCADE, to='locations.city')),
            ],
            options={
                'db_table': 'campuses',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('country', models.ForeignKey(db_column='country_code', on_delete=django.db.models.deletion.CASCADE, to='locations.country')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='department',
            field=models.ForeignKey(db_column='dept_code', on_delete=django.db.models.deletion.CASCADE, to='locations.department'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('coordinator_id', models.CharField(max_length=15, unique=True)),
                ('faculty', models.ForeignKey(db_column='faculty_code', on_delete=django.db.models.deletion.CASCADE, to='locations.faculty')),
            ],
            options={
                'db_table': 'areas',
            },
        ),
    ]
