# Generated by Django 5.2.8 on 2025-11-05 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='locations.city')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'db_table': 'campuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='locations.country')),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.department'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='locations.campus')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'db_table': 'faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='locations.faculty')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'areas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'department')},
        ),
    ]
