# Generated by Django 5.2.8 on 2025-11-07 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='professor',
            field=models.ForeignKey(db_column='professor_id', on_delete=django.db.models.deletion.PROTECT, to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(db_column='NRC', on_delete=django.db.models.deletion.CASCADE, to='academics.group'),
        ),
        migrations.AddField(
            model_name='program',
            name='area',
            field=models.ForeignKey(db_column='area_code', on_delete=django.db.models.deletion.CASCADE, to='locations.area'),
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(db_column='program_code', on_delete=django.db.models.deletion.CASCADE, to='academics.program'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(db_column='subject_code', on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'group')},
        ),
    ]
